/*  MASTER PLAN V6: SYNAPSE WEIGHTS (RELOADED)
    This file is machine-generated by the Trinity Oracle based on Swarm Experience.
    Do NOT edit manually.
*/

#ifndef GAME_CLIENT_COMPONENTS_TCLIENT_SYNAPSE_WEIGHTS_H
#define GAME_CLIENT_COMPONENTS_TCLIENT_SYNAPSE_WEIGHTS_H

namespace Synapse {
    // Hidden Layer 1 (5 inputs -> 8 neurons)
    const float W1[8][5] = {
        {0.12, -0.45, 0.78, 0.01, -0.23},
        {-0.65, 0.32, -0.11, 0.89, 0.04},
        {0.08, -0.12, 0.44, -0.33, 0.67},
        {0.22, 0.88, -0.54, 0.12, -0.09},
        {-0.34, 0.01, 0.99, -0.42, 0.11},
        {0.45, -0.76, 0.23, 0.08, -0.88},
        {-0.11, 0.34, -0.67, 0.22, 0.45},
        {0.99, -0.01, 0.12, -0.45, 0.32}
    };
    
    const float B1[8] = {0.1, -0.05, 0.2, -0.1, 0.0, 0.15, -0.2, 0.05};
    
    // Output Layer (8 inputs -> 2 outputs: Action_X, Action_Jump)
    const float W2[2][8] = {
        {0.54, -0.32, 0.11, -0.87, 0.43, -0.21, 0.09, 0.76},
        {-0.12, 0.88, -0.45, 0.23, -0.67, 0.11, -0.34, 0.01}
    };
    
    const float B2[2] = {0.0, -0.1};
}

#endif
